name: roamio_labs_landing_page
description: "Roamio Labs Landing Page."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  go_router: ^14.2.7
  mesh_gradient: ^1.3.7
  palette_generator: ^0.3.3+4
  fast_immutable_collections: ^10.2.4
  cached_network_image: ^3.4.0
  flutter_tilt: ^3.0.5
  octo_image: ^2.1.0
  provider: ^6.1.2
  flutter_blurhash: ^0.8.2
  flutter_markdown: ^0.7.3+1
  jovial_svg: ^1.1.22
  local_hero: ^0.3.0
  url_launcher: ^6.3.0
  smooth_sheets: ^0.9.4
  animations: ^2.0.11
  intl: ^0.19.0
  jiffy: ^6.3.1
  google_fonts: ^6.2.1
  rxdart: ^0.28.0
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  confetti: ^0.7.0
  freezed_annotation: ^2.4.4
  super_sliver_list: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.3.0
  flutter_lints: ^3.0.1
  firebase_core_platform_interface: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  dependency_validator:
  build_runner: ^2.3.3
  freezed: ^2.5.7
  json_serializable: ^6.6.1
  # test: ^1.24.6
  golden_toolkit: ^0.15.0
  hive_generator: ^2.0.1

  # Routing
  go_router_builder: ^2.3.4
  build_verify: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatars/
    - assets/images/logos/
    - assets/images/backgrounds/
    - assets/images/graphics/
    - assets/images/misc/
    - assets/images/icons/
    - assets/precompiled_svgs/
    - assets/sounds/sound_effects/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/fonts/yellix/

  fonts:
    - family: HgiStrokeRounded
      fonts:
        - asset: assets/fonts/hgi-stroke-rounded.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/InterVariable.ttf
        - asset: assets/fonts/inter/InterVariable-Italic.ttf
          style: italic
    - family: Yellix
      fonts:
        - asset: assets/fonts/yellix/Yellix-Thin.ttf
          weight: 100
        - asset: assets/fonts/yellix/Yellix-Light.ttf
          weight: 300
        - asset: assets/fonts/yellix/Yellix-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/yellix/Yellix-Regular.ttf
          weight: 400
        - asset: assets/fonts/yellix/Yellix-Medium.ttf
          weight: 500
        - asset: assets/fonts/yellix/Yellix-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/yellix/Yellix-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/yellix/Yellix-Bold.ttf
          weight: 700
        - asset: assets/fonts/yellix/Yellix-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/yellix/Yellix-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/yellix/Yellix-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/yellix/Yellix-Black.ttf
          weight: 900
        - asset: assets/fonts/yellix/Yellix-BlackItalic.ttf
          weight: 900
          style: italic


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/icon.png"
  image_path_android: "assets/images/logos/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/avatars/340x340.webp"
    # background_color: "#00FFFFFF"
    theme_color: "#ffffff"
  macos:
    generate: true
    image_path: "assets/images/avatars/340x340.webp"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/avatars/340x340.png
  color_dark: "#222222"
  image_dark: assets/images/avatars/340x340.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
